columns:
  age: int64
  work_class: str
  fnlwgt: int64
  education: str
  education_num: int64
  marital_status: str
  occupation: str
  relationship: str
  race: str
  sex: str
  capital_gain: int64
  capital_loss: int64
  country: str
  salary: str
  hours_per_week: int64

numerical_columns:
  - age
  - capital_gain
  - capital_loss
  - hours_per_week

categorical_columns:
  - work_class
  - education
  - marital_status
  - occupation
  - relationship
  - race
  - sex

no_of_column: 15


target_column: salary

domain_value:
  salary:
    - "<=50K"
    - ">50K"